### ISSUE TITLE
"Google.Protobuf.InvalidProtocolBufferException" During Login

### ISSUE THREAD

**Issue by ConnorVG** [PocketMobsters/PokeMobBot#1]
I get this issue on one of my Dedicated Server (Windows Server 2012). No idea what is causing it. The setups are all the same as far as I can tell. Fresh boxes w/ shared network drives.

```
Initializing Rocket logger at time 7/31/2016 1:40:52 AM...
[01:40:55] Perfect! You already have the newest Version 0.5.0
[01:40:55] Logging in using Google
[01:40:56] Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36
```

**Comment by mafimchen** [comment]
some situation, hope it solved soon.

**Comment by badios176** [comment]
Same here

**Comment by mafimchen** [comment]
Azure Microsoft, creating a new Win 7/10 to check whether not compatible with win 2012.

**Comment by Stormsys** [comment]
Got the issue on AWS, ran the bot on my pc and its fine - clearly niantec have just blocked a bunch of cloud providers.

**Comment by badios176** [comment]
@Stormsys Are we definitly sure about this? Or is it a guess

**Comment by Stormsys** [comment]
Its a guess - but it seems pretty likely - i'm running the same code on both places with the same config.

**Comment by LesterLyu** [comment]
Same exception with aws server(Windows Server 2012)

**Comment by mafimchen** [comment]
tired win 7 on Azure, same result, so maybe like Stormsys said, they block some cloud server

**Comment by LesterLyu** [comment]
@Stormsys is right, access https://pgorelease.nianticlabs.com/plfe/rpc shows 403 Forbidden on the server.

**Comment by Zeift** [comment]
For now I'm using VPN

**Comment by boboyrex** [comment]
Same here
I use Windows Server 2012 (Azure)

**Comment by PocketMobsters** [comment]
Niantic indeed did block a lot of cloud providers in an attempt to defeat botfarms.

**Comment by Encamy** [comment]
How can I connect to instance if I use VPN (what IP adress should I use?)

**Comment by thecoolkogut4** [comment]
I'm getting the exact same thing on aws

**Comment by chakuze** [comment]
me too (AWS), they blocked our fun :(

**Comment by Encamy** [comment]
I found solution!
I update firmwre at wifi router to dd-wrt
Then I have set up VPN
After that I create VPN connection at instance (amazon aws)
The next step - to run the bot
Bot works excellent!
P.S. sorry for my english. Hope it will be usefull
