### ISSUE TITLE
Getting GoogleOfflineException from multiple locations for all accounts

### ISSUE THREAD

**Issue by Yokomoko** [PocketMobsters/PokeMobBot#119]
Getting a GoogleOfflineException on 2 different accounts from multiple locations in the UK. Any ideas? I can log into the game and on to the google account fine and it isn't using 2-step verification (which I've tried and still doesn't work).

I've debugged it and it throws the exception on the second 'Auth' check (oAuth?) in the Rocket API. I've tried removing the !Contains"Auth" check and it throws another exception. 

Any ideas? Are there any different ports I can use or addresses etc.?

**Comment by Yokomoko** [comment]
Further to this, the full exception is:

`[08:58:59] (ERROR) PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exception of type 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' was thrown.
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 33
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36`

Seems to be pointing to a strange directory??

**Comment by Afraidium** [comment]
Make sure your username and password are correct, if you have two factor authentication enabled, make an application specific password. Also make sure in your auth file, you have username and password in double quotes ""

**Comment by Yokomoko** [comment]
It comes up with a different error message when the username and password are incorrect. It is half authenticating but not the other half.
