### ISSUE TITLE
Bot .exe crashing periodically

### ISSUE THREAD

**Issue by Sasstraliss** [PocketMobsters/PokeMobBot#179]
I run about 8 instances of the bot. 

About every 30 minutes to an hour, one of them crashes. (.exe has encountered a problem and has stopped, etc)

This was an issue with the later releases of Necro as well.

**Comment by adamncsu** [comment]
Mine are crashing on API errors too. Necro used a fork of the API that caught all errors. MobBot needs to do the same.

**Comment by Fenixxia** [comment]
https://github.com/PocketMobsters/PokeMobBot/issues/186

Similarly. Also faced this problem in the new version, as in the old.

**Comment by badios176** [comment]
I'm also having problems with it, it crashes periodically

**Comment by Muzurio** [comment]
same problem here ( had the same with Neco 0.4.0 version). It happens exactly at 30 minute mark. All my 6 bots show an error that there servers are busy and every now and then one of the crashes. I guess it has to do with the fix that was implemented to circumvent the timeout after 30 minutes.

**Comment by badios176** [comment]
I noticed that it happens only with my PTC accounts. Not with google account, how about you guys?

**Comment by Muzurio** [comment]
i am only using PTC accounts

**Comment by Muzurio** [comment]
It just happend again, i managed to copy the output:
`15:54:52] (TRANSFERED) Rattata - CP: 96  IV: 47.33%   [Best CP: 401  IV: 75.87%] (Candies: 12)
[15:55:05] (ERROR) Niantic Servers unstable, throttling API Calls.
[15:55:06] (TRANSFERED) Magikarp        - CP: 95  IV: 64.07%   [Best CP: 19  IV: 95.44%] (Candies: 251)

Unhandled Exception: PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown.
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Common\ApiFailureStrategy.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
`

**Comment by pzinsta** [comment]
Crashed in 30 minutes as well.
Here's the last line in the log:

> [18:21:14] Niantic Servers unstable, throttling API Calls.

P.S.  
>  "AuthType": "ptc"

**Comment by lyrex** [comment]
Happening when relogging after 30 Minutes (timeout) and then PTC login error.
I've made up already a fix for it but I currently can't test it since the servers are down.

**Comment by Arptastic** [comment]
Can you give us the fix?

**Comment by chauhan-rahul** [comment]
it not 30minutes but something like 90minutes for me and always the **PTC** login... google login keeps working perfectly for hours and hours!
