### ISSUE TITLE
Unhandel Exception, no user named trent

### ISSUE THREAD

**Issue by Kampfhamster** [PocketMobsters/PokeMobBot#186]
Unhandled Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Common\ApiFailureStrategy.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Fenixxia** [comment]
https://github.com/PocketMobsters/PokeMobBot/issues/179
Similarly. Also faced this problem in the new version, as in the old.

**Comment by DurtyFree** [comment]
Lets continue the discussion in the other issue ( #179 )
