### ISSUE TITLE
can't run it i m on win 10 64bit

### ISSUE THREAD

**Issue by ganeshisking** [PocketMobsters/PokeMobBot#20]
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path '', line 1, position 10.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at PoGo.PokeMobBot.Logic.AuthSettings.Load(String path) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Settings.cs:line 44
   at PoGo.PokeMobBot.Logic.GlobalSettings.Load(String path) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Settings.cs:line 465
   at PoGo.PokeMobBot.CLI.Program.Main(String[] args) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.CLI\Program.cs:line 33

**Comment by ShallowHacker** [comment]
Mine runs fine. It's saying you fucked up a config.

**Comment by jakesmurf** [comment]
Start over from scratch and be careful not to change any of the characters in the settings file.  It looks like you accidentally added/deleted something from the settings file and the bot can't read it properly anymore.

**Comment by ganeshisking** [comment]
Yep working fine now
