### ISSUE TITLE
Error when reducing Delays

### ISSUE THREAD

**Issue by ruturajvy** [PocketMobsters/PokeMobBot#204]
[13:16:32] (ERROR) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobB
ot\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.
PokeMobBot.Logic\State\FarmState.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo
.PokeMobBot.Logic\State\StateMachine.cs:line 36

Does anyone know how to fix this?

**Comment by Fenixxia** [comment]
You have something incorrect in the config. Try to install the program from the beginning. Fix the config file manually and step by step to check after any changes will appear this error.

**Comment by DurtyFree** [comment]
This is a config  related issue.
