### ISSUE TITLE
(ERROR) System.Net.WebException: The operation has timed out

### ISSUE THREAD

**Issue by MINEREAPER** [PocketMobsters/PokeMobBot#235]
I am getting this error every time it snipes any points , it continues for 5-10 times and finally gets something 
`[22:37:39] (SNIPER) Scanning for Snipeable Pokemon at 51.507351,-0.127758...
[22:37:44] (ERROR) System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\rober\Desktop\Pokermon GO\0000\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 337
[22:37:44] (INFO) No Pokemon found to snipe!`

**Comment by legend6868** [comment]
@MINEREAPER It happened to me as well. Always no pokemon found to snipe. all the time.

**Comment by MINEREAPER** [comment]
Thats sad , it reduces my xp/h to 60-80k sometimes...

**Comment by DurtyFree** [comment]
Sniping is currently in work, the next release will address this issue.
