### ISSUE TITLE
Latest build of pokemobbot - ArgumentNullException

### ISSUE THREAD

**Issue by Xander567** [PocketMobsters/PokeMobBot#258]
```
[19:24:53] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Envelopes.RequestEnvelope.Types.AuthInfo.Types.JWT.set_Contents(String value)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequestEnvelope(Request[] customRequests) in C:\Users\Xander\Documents\git\Bot2\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 49
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\Xander\Documents\git\Bot2\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\Xander\Documents\git\Bot2\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Xander\Documents\git\Bot2\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Xander\Documents\git\Bot2\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36
```

**Comment by chauhan-rahul** [comment]
hapened to me, while the servers were down.. try again... it started working as soon as the servers were back!!

**Comment by DurtyFree** [comment]
Doesnt seem like a error related to us.

**Comment by Xander567** [comment]
I posted it so it could be handled properly. Unhandled exceptions are ugly.
