### ISSUE TITLE
Always experiencing this error during logging in

### ISSUE THREAD

**Issue by masterpowers** [PocketMobsters/PokeMobBot#306]
[08:37:38] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Helpers\JsonHelper.cs:line 10
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36

**Comment by toliman** [comment]
is your ptc username/password in quotes ?
