### ISSUE TITLE
unknown issue when running the program

### ISSUE THREAD

**Issue by DerekCL** [PocketMobsters/PokeMobBot#31]
I keep getting this error when running the application every so often

02:42:22] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\LevelUpPokemonTask.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36
[02:42:22] Logging in using Google

what might be the issue?

**Comment by bmdr38** [comment]
Well, the current iteration of the upgrade task is pretty terrible.  But in this case, it is choking on the fact that you (probably) have a pokemon that is at its at its max level and cannot be upgraded at this time.  If you are coding inclined and want a quick fix, you can remove the logging line that is throwing this.  Otherwise you should disable upgrading until either my PR is accepted or it is fixed by another

**Comment by lilsizzle** [comment]
I have the same issue too.

**Comment by DerekCL** [comment]
Thanks for the response I will wait for a fix.

**Comment by UntilSunrise** [comment]
duplicate
