### ISSUE TITLE
New Update Crash on Start - 'potionsToKeepIncorrect' 

### ISSUE THREAD

**Issue by eye-drop** [PocketMobsters/PokeMobBot#315]
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "potionsToKeepIncorrect" to type 'PoGo.PokeMobBot.Logic.Common.TranslationString'. Path 'TranslationStrings[73].Key', line 296, position 37. ---> System.ArgumentException: Requested value 'potionsToKeepIncorrect' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PoGo.PokeMobBot.Logic.Common.Translation.Load(ILogicSettings logicSettings) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Common\Translations.cs:line 557
   at PoGo.PokeMobBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\Session.cs:line 32
   at PoGo.PokeMobBot.CLI.Program.Main(String[] args)

**Comment by TVsIan** [comment]
I'm getting the same error on both 1.1.0 and 1.1.2. I've tried installing from the zip and using the auto update, either way does the same thing.

**Comment by eye-drop** [comment]
If you want to use it until it is fixed. Rename PokeMobBot.exe to PokeMobBot.exe.1.1.2 and rename PokeMobBot.exe.old to PokeMobBot.exe it will work. Simple fix until this error goes away

**Comment by AzNJDM** [comment]
Getting the same error to

**Comment by domuk** [comment]
Same issue here.

**Comment by dragobite** [comment]
Same here, any solutions besides using the old client?

**Comment by domuk** [comment]
I just deleted everything and downloaded the release again, new configurations and files have fixed the issue. Seems something from an older version didn't upgrade smoothly.

**Comment by Daylend** [comment]
v1.1.3 has this issue fixed. You can download it from here: https://github.com/PocketMobsters/PokeMobBot/releases/tag/v1.1.3

If you're still getting this problem in v1.1.3 somehow, delete the Translations folder in the Config folder.
