### ISSUE TITLE
Sniper error

### ISSUE THREAD

**Issue by legend6868** [PocketMobsters/PokeMobBot#341]
[14:18:40] SkipLagged is down or SnipeRequestTimeoutSeconds is too small!
[14:18:45] System.Net.WebException: The remote name could not be resolved: 'pokesnipers.com'
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Start>d__10.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 498

I got this issue. Anyone can help?

**Comment by tangdami** [comment]
I updated to the latest release. But I also noticed that PokeSnipers.com is not offering any cords for rare pokemons now, it was redirected to a EUR 3.95 website... Any other similar website for replacement?

**Comment by yogyantoro** [comment]
Try pokeWatchers

**Comment by yogyantoro** [comment]
Pokewatchers.com

**Comment by Walawalawala** [comment]
where would I add that yog?

**Comment by Daylend** [comment]
You shouldn't have "UseSnipeLocationServer" and "UsePokeSnipersLocationServer" both set to true.

SkipLagged has been down for awhile, not a problem with our code. Us supporting pokesnipers.com seems to have brought down the site.

We may consider switching again.

**Comment by legend6868** [comment]
@Daylend Cheers. l'm looking forward to waiting for your product. many thanks.
