### ISSUE TITLE
Unkown error with snipepokemontask.

### ISSUE THREAD

**Issue by notwalex** [PocketMobsters/PokeMobBot#367]
Hello, 
I'm getting this now and then, no sniping, in rest all seems to work.

Thank you,
R

[10:00:19] System.Net.WebException: The remote server returned an error: (522) Origin Connection Time-out.
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Start>d__10.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 498

**Comment by notwalex** [comment]
NVM i found the a closed issue with the refference.
