### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by StevePavlin** [PocketMobsters/PokeMobBot#421]
Another error after running for some time:

https://i.gyazo.com/5c40a1c3961ada469cc89fc0dc182d3e.png

**Comment by jinkawasaki333** [comment]
Probably something is wrong with your Auth.json. Try to recheck it again.

**Comment by lyrex** [comment]
Try to delete the english translation file in your translation folder and then run the bot.
It will recreate it

**Comment by Muzurio** [comment]
Got same problem. I run 6 bots continously and every now and then one crashes with the same error message, see below.

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Envelopes.RequestEnvelope.Types.AuthInfo.Types.JWT.set_Contents(String value)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequestEnvelope(Request[] customRequests) in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 49
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Common\ApiFailureStrategy.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
