### ISSUE TITLE
Bot won't run.

### ISSUE THREAD

**Issue by pokepuff** [PocketMobsters/PokeMobBot#482]
Tried with three different accounts and my config seems to be fine but every time I start up the bot on one I get this in red:

 [18:00:07]
 System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.PokeMobBot.Logic.Inventory.<GetPokemonToEvolve>d__29.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Inventory.cs:line 382
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.EvolvePokemonTask.<Execute>d__1.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\EvolvePokemonTask.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37

My config.
> {
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "DumpPokemonStats": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "StartupWelcomeDelay": false,
  "TranslationLanguageCode": "en",
  "WebSocketPort": 14251,
  "Teleport": false,
  "DefaultLatitude": 48.862522,
  "DefaultLongitude": 2.343536,
  "DefaultAltitude": 10.0,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "MaxTravelDistanceInMeters": 1500,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "DelayBetweenPlayerActions": 2000,
  "DelayPositionCheckState": 2000,
  "DelayPokestop": 1000,
  "DelayCatchPokemon": 1000,
  "DelayBetweenPokemonCatch": 2000,
  "DelayCatchNearbyPokemon": 1000,
  "DelayCatchLurePokemon": 1000,
  "DelayCatchIncensePokemon": 1000,
  "DelayEvolvePokemon": 1000,
  "DelayEvolveVariation": 0.3,
  "DelayTransferPokemon": 1000,
  "DelayDisplayPokemon": 1000,
  "DelayUseLuckyEgg": 1000,
  "DelaySoftbanRetry": 1000,
  "DelayRecyleItem": 1000,
  "DelaySnipePokemon": 1000,
  "MinDelayBetweenSnipes": 6000,
  "SnipingScanOffset": 0.003,
  "UseEggIncubators": true,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "TransferDuplicatePokemon": true,
  "PrioritizeIvOverCp": true,
  "KeepMinCp": 1800,
  "KeepMinIvPercentage": 95.0,
  "KeepMinDuplicatePokemon": 2,
  "KeepPokemonsThatCanEvolve": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAboveIvValue": 95.0,
  "UseLuckyEggsWhileEvolving": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "AutomaticallyLevelUpPokemon": false,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "HumanizeThrows": false,
  "ThrowAccuracyMin": 0.5,
  "ThrowAccuracyMax": 1.0,
  "ThrowSpinFrequency": 0.75,
  "MaxPokeballsPerPokemon": 6,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.25,
  "UseMasterBallBelowCatchProbability": 0.05,
  "UsePokemonToNotCatchFilter": false,
  "UseBerryMinCp": 450,
  "UseBerryMinIv": 95.0,
  "UseBerryBelowCatchProbability": 0.2,
  "AutoFavoritePokemon": false,
  "FavoriteMinIvPercentage": 95.0,
  "TotalAmountOfPokeballsToKeep": 250,
  "TotalAmountOfPotionsToKeep": 60,
  "TotalAmountOfRevivesToKeep": 30,
  "TotalAmountOfBerriesToKeep": 35,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "UseSnipeLocationServer": true,
  "UsePokeSnipersLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "SnipeRequestTimeoutSeconds": 5,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Dragonite": {
      "KeepMinCp": 2800,
      "KeepMinIvPercentage": 99.0,
      "KeepMinDuplicatePokemon": 1
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "charmeleon",
      "wartortle",
      "raichu",
      "kadabra",
      "farfetchd",
      "seel",
      "shellder",
      "gastly",
      "voltorb",
      "koffing",
      "chansey",
      "kangaskhan",
      "mrMime",
      "pikachu",
      "squirtle",
      "abra",
      "electabuzz",
      "aerodactyl",
      "magmar",
      "grimer",
      "blastoise",
      "nidorina",
      "machop",
      "geodude",
      "muk",
      "lickitung",
      "chansey",
      "lapras",
      "ditto",
      "vulpix",
      "kabuto",
      "porygon",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "dratini",
      "dragonair",
      "charmander",
      "mew",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by nerclid** [comment]
Same issue, except I had had the bot running for a while today, and it stopped and began constantly throwing that same error. 

`[18:13:38] Playing as --OMITTED--
[18:13:38] Make sure Lat & Lng are right. Exit Program if not! Lat: --OMITTED-- Lng: --OMITTED--
[18:13:38] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Inventory.<GetPokemons>d__26.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Inventory.cs:line 331
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Inventory.<GetHighestsCp>d__16.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Inventory.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37`

**Comment by jinkawasaki333** [comment]
I got the same problem yesterday. I think it has nothing to do with the config.

What I did was deleting the folder (but keeping Auth.json and Config.json), and re-extract the files fresh from the latest release, and it worked for me.

**Comment by nerclid** [comment]
Seems this is happening when my inventory is full.

**Comment by Valmere** [comment]
Open a new issue if this problem persists after the next release.
