### ISSUE TITLE
Sniping leaving you at sniped location after an error

### ISSUE THREAD

**Issue by Krotain** [PocketMobsters/PokeMobBot#499]
When sniping if there is a network throttling error or an exception that causes the bot to restart it keeps your location at the sniped location.  This has only happened to me three times and I'm not 100% sure how to recreate this other than getting an error during sniping.  

1st time
[12:58:25] [Sniper] Sniping a Poliwrath with unknown IV at 40.773428,-73.967806...
[12:58:33] Niantic Servers unstable, throttling API Calls.
[12:58:35] Incubator status update: 2.90km left
[12:58:35] Incubator status update: 7.20km left
[12:58:35] You're outside of your defined radius! Walking to start (332339.169803488m away) in 5 seconds. Is your Coords.ini file correct?

2nd time
[20:59:02] [Sniper] Sniping a Chansey with 87 IV at 20.566925,-100.415206...
[20:59:10] System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Map.cs:line 69
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Snipe>d__7.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.SnipePokemonTask.<Execute>d__6.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\SnipePokemonTask.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in G:\GIT_Projects\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() in G:\GIT_Projects\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Map.cs:line 69<---

[20:59:10] Logging in using account Google
[20:59:11] Playing as KroTrain
[20:59:11] Make sure Lat & Lng are right. Exit Program if not! (removed my coords)
removed pokemon cause too long
[20:59:12] Rattata successfully for 500xp
[20:59:13] Raticate	- CP: 570  IV: 58.82%   [Best CP: 804  IV: 87.05%] (Candies: 3)
[20:59:14] Incubator status update: 0.25km left
[20:59:14] Incubator status update: 2.09km left
[20:59:14] You're outside of your defined radius! Walking to start (3029515.00717638m away) in 5 seconds. Is your Coords.ini file correct?

3rd time
[22:01:50] [Sniper] Sniping a Dragonite with 74 IV at 39.562773,-104.942308...
[22:01:58] Niantic Servers unstable, throttling API Calls.
[22:01:58] Weedle successfully for 500xp
[22:01:59] Pidgey	- CP: 186  IV: 52.13%   [Best CP: 120  IV: 64.17%] (Candies: 12)
[22:02:00] Pidgey	- CP: 424  IV: 17.86%   [Best CP: 120  IV: 64.17%] (Candies: 13)
[22:02:01] Porygon	- CP: 218  IV: 75.14%   [Best CP: 676  IV: 100.00%] (Candies: 753)
[22:02:01] Kakuna	- CP: 237  IV: 29.27%   [Best CP: 259  IV: 79.64%] (Candies: 4)
[22:02:01] Staryu	- CP: 415  IV: 87.27%   [Best CP: 319  IV: 97.14%] (Candies: 1364)
[22:02:02] [Inventory] Pokeballs: 102 | Greatballs: 3 | Ultraballs: 2 | Masterballs: 0
[22:02:02] [Inventory] Potions: 1 | Super Potions: 1 | Hyper Potions: 0 | Max Potions: 80
[22:02:04] 7x ItemPokeBall
[22:02:04] 1x ItemPotion
[22:02:05] 1x ItemSuperPotion
[22:02:06] Incubator status update: 0.51km left
[22:02:06] Incubator status update: 0.24km left
[22:02:06] You're outside of your defined radius! Walking to start (2397264.02995097m away) in 5 seconds. Is your Coords.ini file correct?

**Comment by rbusk7** [comment]
how do you get it to snipe? tried setting "usesnipelocationserver" and "usepokesnipelocationserver" to true (not at same time) and it never attempted to snipe. i have it set to go snipe after 60 seconds and never did after 5 min of running

**Comment by FatSacks** [comment]
I've experienced the same thing several times now.

**Comment by Roenbaeck** [comment]
I am also getting "You're outside of your defined radius!" sometimes after sniping, which would not be a problem if the bot actually did what it is saying it will do, "walking to start in 5 seconds". However, it seems like a restart is required to get out of this situation.

**Comment by y2krazy** [comment]
Same thing here! "Walking back" for the last 3½ hours. >_<
![pokemobbot_2016-08-03_06-49-48](https://cloud.githubusercontent.com/assets/12468950/17364565/7ab57f64-5946-11e6-9a5e-15ac03a8bb67.png)

**Comment by petacz** [comment]
The same problem here:
[20:27:17] (INFO) [Sniper] Sniping a Gyarados with unknown IV at 60.805288,11.025158...
[20:28:57] (ERROR) Current Operation was canceled.
[20:28:57] (INFO) Logging in using account Ptc
[20:29:00] (INFO) Playing as XXX
[20:29:00] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 60.805288 Lng: 11.025158
[20:29:00] (INFO) ====== DisplayHighestsCP ======
XXX
[20:29:01] (INFO) ====== DisplayHighestsPerfect ======
XXX
[20:29:03] (TRANSFER) Jolteon   - CP: 1631  IV: 92.25%   [Best CP: 30  IV: 94.94%] (Candies: 538)
[20:29:03] (EGG) Incubator status update: 3.92km left
[20:29:03] (ATTENTION) You're outside of your defined radius! Walking to start (1214019.73904538m away) in 5 seconds. Is your Coords.ini file correct?
