### ISSUE TITLE
System Null Reference Exeption end of stack: TaksAwaiter.ThrowForNonSuccess

### ISSUE THREAD

**Issue by Kampfhamster** [PocketMobsters/PokeMobBot#550]
[20:56:47] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Inventory.<GetPokemons>d__26.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Inventory.cs:line 353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by gesshuh** [comment]
same here, big error loop, bot wont work anymore

**Comment by gesshuh** [comment]
had the same problem, i evolved a few pokemon manually and it worked after that, not sure if this is the solution but u can try for sure ;)

**Comment by Valmere** [comment]
Tagging as a bug for reference and closing, if the error occurs again after the bot has been updated make another issue.
