### ISSUE TITLE
Unknown Issues 

### ISSUE THREAD

**Issue by BackBlues** [PocketMobsters/PokeMobBot#60]
[12:14:54] System.IO.IOException: The process cannot access the file 'C:\Users\***\Downloads\PoGoNew\Release\Logs\NecroBot-2016-07-31-12.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at PoGo.PokeMobBot.Logic.Logging.Logger.Log(String message) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Logging\Logger.cs:line 20
   at PoGo.PokeMobBot.Logic.Logging.Logger.Write(String message, LogLevel level, ConsoleColor color) in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Logging\Logger.cs:line 64
   at PoGo.PokeMobBot.Logic.Inventory.<GetItemsToRecycle>d__19.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Inventory.cs:line 255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.Tasks.RecycleItemsTask.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\RecycleItemsTask.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36
[12:14:54] Logging in using Google

It look like that the bot can't acces NecroBot-2016-07-31-12.txt but there is no other programm that acces this txt

**Comment by DurtyFree** [comment]
Do other people experienced this too?

**Comment by mvegter197** [comment]
Can confirm it:
https://gyazo.com/e66e2060fb4e629b9257d6bfb4131e7a

**Comment by BackBlues** [comment]
I Maybe found the Problem, it was maybe ByteDefence (Anti Malware distributed with other software)

**Comment by mvegter197** [comment]
I'm not running any anti virus or malware nor do I have winodwos defender on, yet I experience the same error.

**Comment by Afraidium** [comment]
Sounds like there is another bot process running that is accessing the file.
@DurtyFree Close?
