### ISSUE TITLE
Possible bug with new pull

### ISSUE THREAD

**Issue by KAustin1** [PocketMobsters/PokeMobBot#69]
pulled in the current changes and began getting this 

[07:02:36] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Tasks.CatchPokemonTask.<Execute>d__0.MoveNext() in C:\Users\medic\OneDrive\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\CatchPokemonTask.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\medic\OneDrive\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\medic\OneDrive\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\medic\OneDrive\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\medic\OneDrive\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 36

**Comment by MiaoMFoo** [comment]
same

**Comment by PocketMobsters** [comment]
The main GitHub repo doesn't necessarily always stay stable, but the releases put out are. I'm working on some stuff but was sidetracked by the drama on Reddit and such.

**Comment by KAustin1** [comment]
not an issue, i knew the Dev Team would get to it when they could. just wanted to make sure it was noted..
