### ISSUE TITLE
Bot erroring out

### ISSUE THREAD

**Issue by lgndz** [PocketMobsters/PokeMobBot#75]
I dont know if it matters, but the path listed says users/Trent/ and that is incorrect and not from my PC

"06:29:38] (RECYCLING) 8x ItemPokeBall
[06:29:39] (RECYCLING) 3x ItemPotion
[06:29:39] (RECYCLING) 1x ItemRevive
[06:29:40] (RECYCLING) 1x ItemRazzBerry
[06:29:41] (INFO) Arriving to Pokestop: Day In Day Out in (83m)

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Envelopes.RequestEnvelope.Types.AuthInfo.Types.JWT.set_Contents(String value)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetInitialRequestEnvelope(Request[] customRequests) in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 49
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.PokeMobBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Common\ApiFailureStrategy.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()"

**Comment by daanh99** [comment]
I have a similar issue, the path listed says C:\Users\Trent\ too, and that folder doesn't exist on my PC.

```
[15:33:28] System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij PoGo.PokeMobBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\LevelUpPokemonTask.cs:regel 61
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:regel 26
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bij PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:regel 36
```

**Comment by Afraidium** [comment]
Rocket API issue? I have no idea why this is going that. Need more info.

**Comment by lgndz** [comment]
Like? There were no other issues

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Tue, Aug 2, 2016 at 12:53 AM -0400, "Afraidium (Andrew B.)" <notifications@github.com> wrote:












Rocket API issue? I have no idea why this is going that. Need more info.
